const customeFeild = {
  className: "blueBoarder",
  field: [
    {
      inputType: "text",
      name: "surname",
      isRequired: true,
      className: "blueBoarder",
      placeholder: "Surname",
      value: "",
    },
    {
      inputType: "text",
      name: "initial",
      isRequired: true,
      className: "blueBoarder",
      placeholder: "Initial",
      value: "",
    },
    {
      inputType: "number",
      name: "year",
      isRequired: true,
      className: "blueBoarder",
      placeholder: "Year",
      value: "",
    },
    {
      inputType: "text",
      name: "titleOfArticle",
      isRequired: true,
      className: "blueBoarder",
      placeholder: "Title of article",
      value: "",
    },
    {
      inputType: "text",
      name: "titleOfJournal",
      isRequired: true,
      className: "blueBoarder",
      placeholder: "Title of Journal",
      value: "",
    },
    {
      inputType: "text",
      name: "volume",
      isRequired: false,
      className: "blueBoarder",
      placeholder: "Volume",
      value: "",
    },
    {
      inputType: "number",
      name: "issueNumber",
      isRequired: false,
      className: "blueBoarder",
      placeholder: "Issue Number",
      value: "",
    },
    {
      inputType: "number",
      name: "pageNumber",
      isRequired: true,
      className: "blueBoarder",
      placeholder: "Page Number",
      value: "",
    },
  ],
};
export default customeFeild;
