const customeFeild = {
  inputType: "text",
  name: "author",
  isRequired: true,
  className: "blueBoarder",
  placeholder: "Author",
  field: [
    {
      inputType: "text",
      name: "author",
      isRequired: true,
      className: "blueBoarder",
      placeholder: "Author",
      value: "",
    },
    {
      inputType: "text",
      name: "initial",
      isRequired: true,
      className: "blueBoarder",
      placeholder: "Initial",
      value: "",
    },
    {
      inputType: "number",
      name: "year",
      isRequired: true,
      className: "blueBoarder",
      placeholder: "Year",
      value: "",
    },
    {
      inputType: "text",
      name: "title",
      isRequired: true,
      className: "blueBoarder",
      placeholder: "Title",
      value: "",
    },
    {
      inputType: "text",
      name: "edition",
      isRequired: false,
      className: "blueBoarder",
      placeholder: "Edition",
      value: "",
    },
    {
      inputType: "text",
      name: "publisher",
      isRequired: true,
      className: "blueBoarder",
      placeholder: "Publisher",
      value: "",
    },
    {
      inputType: "text",
      name: "place",
      isRequired: true,
      className: "blueBoarder",
      placeholder: "Place",
      value: "",
    },
  ],
};
export default customeFeild;
